//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.31 at 10:52:06 PM MSK 
//


package com.epam.brest.course2015.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.epam.brest.course2015.core.Cardto;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://epam.com/brest/course2015/core}cardto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardto"
})
@XmlRootElement(name = "GetCarDtoResponse")
public class GetCarDtoResponse {

    @XmlElement(namespace = "http://epam.com/brest/course2015/core", required = true)
    protected Cardto cardto;

    /**
     * Gets the value of the cardto property.
     * 
     * @return
     *     possible object is
     *     {@link Cardto }
     *     
     */
    public Cardto getCardto() {
        return cardto;
    }

    /**
     * Sets the value of the cardto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cardto }
     *     
     */
    public void setCardto(Cardto value) {
        this.cardto = value;
    }

}
