//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 10:44:11 AM MSK 
//


package com.epam.brest.course2015.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.epam.brest.course2015.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.epam.brest.course2015.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCarByIdRequest }
     * 
     */
    public GetCarByIdRequest createGetCarByIdRequest() {
        return new GetCarByIdRequest();
    }

    /**
     * Create an instance of {@link GetCarByIdResponse }
     * 
     */
    public GetCarByIdResponse createGetCarByIdResponse() {
        return new GetCarByIdResponse();
    }

    /**
     * Create an instance of {@link GetCarDtoResponse }
     * 
     */
    public GetCarDtoResponse createGetCarDtoResponse() {
        return new GetCarDtoResponse();
    }

    /**
     * Create an instance of {@link UpdateCarRequest }
     * 
     */
    public UpdateCarRequest createUpdateCarRequest() {
        return new UpdateCarRequest();
    }

    /**
     * Create an instance of {@link UpdateCarResponse }
     * 
     */
    public UpdateCarResponse createUpdateCarResponse() {
        return new UpdateCarResponse();
    }

    /**
     * Create an instance of {@link GetCarDtoRequest }
     * 
     */
    public GetCarDtoRequest createGetCarDtoRequest() {
        return new GetCarDtoRequest();
    }

}
